server:
   port: 8081
spring:
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true 
   datasource:
     url: jdbc:mysql://localhost:3306/TheDigitalKey?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=True
     username: root
     password: root